version: '3.8'

services:
  # This is the Redis Database Service
  redis:
    image: redis/redis-stack:latest
    container_name: social_media_redis
    ports:
      - "6379:6379"  # The port your NestJS app connects to
      - "8001:8001"  # The port for the Visual Dashboard (UI)
    volumes:
      - redis_data:/data # Saves your data so it isn't lost when you restart
    restart: always

volumes:
  redis_data: